// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.4.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace SpecFlowTests.WhoCanHelpMe.Web_Controllers.ProfileControllerFeatures
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.4.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Creating a profile")]
    public partial class CreatingAProfileFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreatingANewProfile.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Creating a profile", "In order to publicise my skills\r\nAs a user\r\nI want to create my profile", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Requesting the create page")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void RequestingTheCreatePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Requesting the create page", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("I am creating a new profile");
#line 9
testRunner.When("I request the Create page");
#line 10
testRunner.Then("the default view should be returned");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating a profile")]
        public virtual void CreatingAProfile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating a profile", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
testRunner.Given("I am creating a new profile");
#line 14
testRunner.And("I have set my first name to FirstName");
#line 15
testRunner.And("I have set my surname to Surname");
#line 16
testRunner.When("I submit my data to the Create page");
#line 17
testRunner.Then("my profile should be created");
#line 18
testRunner.And("I should be directed to the update profile page");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating a profile with invalid first name")]
        public virtual void CreatingAProfileWithInvalidFirstName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating a profile with invalid first name", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
testRunner.Given("I am creating a new profile");
#line 22
testRunner.And("I have left my first name blank");
#line 23
testRunner.And("I have set my surname to Surname");
#line 24
testRunner.When("I submit my data to the Create page");
#line 25
testRunner.Then("I should be directed to the create profile page");
#line 26
testRunner.And("the invalid first name error message should be shown");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating a profile with invalid last name")]
        public virtual void CreatingAProfileWithInvalidLastName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating a profile with invalid last name", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
testRunner.Given("I am creating a new profile");
#line 30
testRunner.And("I have left my first name FirstName");
#line 31
testRunner.And("I have set my surname to blank");
#line 32
testRunner.When("I submit my data to the Create page");
#line 33
testRunner.Then("I should be directed to the create profile page");
#line 34
testRunner.And("the invalid last name error message should be shown");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating a profile with invalid first and last names")]
        public virtual void CreatingAProfileWithInvalidFirstAndLastNames()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating a profile with invalid first and last names", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
testRunner.Given("I am creating a new profile");
#line 38
testRunner.And("I have left my first name blank");
#line 39
testRunner.And("I have set my surname to blank");
#line 40
testRunner.When("I submit my data to the Create page");
#line 41
testRunner.Then("I should be directed to the create profile page");
#line 42
testRunner.And("the invalid first name error message should be shown");
#line 43
testRunner.And("the invalid last name error message should be shown");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
